---
- name: Install required packages
  apt:
    name:
      - slapd
      - ldap-utils
      - schema2ldif

- name: Check if mdb was wiped
  stat:
    path: "{{ mdbwiped_flag }}"
  register: mdbwiped

- name: Wipe default mdb
  file:
    path: "{{ slapd_mdb_dir }}"
    state: absent
  when: not mdbwiped.stat.exists

- name: Create slapd mdb location
  file:
    path: "{{ slapd_mdb_dir }}"
    state: directory
    owner: "{{ slapd_user }}"
    group: "{{ slapd_group }}"
    mode: 0770

- name: Create mdb wipe flag
  file:
    path: "{{ mdbwiped_flag }}"
    state: touch
  when: not mdbwiped.stat.exists

- name: Create slapd OLC location
  file:
    path: "{{ slapd_olc_dir }}"
    state: directory
    owner: "{{ slapd_user }}"
    group: "{{ slapd_group }}"
    mode: 0770

- name: Create slapd unit
  template:
    src: slapd.service.j2
    dest: /etc/systemd/system/slapd.service
    mode: 0644
  register: unitfile

- name: Enable slapd unit
  service:
    name: slapd.service
    enabled: yes

- name: Create tmpfiles config
  template:
    src: tmpfiles.conf.j2
    dest: /etc/tmpfiles.d/slapd.conf
  register: tmpfiles

- name: Reload systemd
  command: /bin/systemctl daemon-reload
  when: unitfile.changed

- name: Create tmpfiles
  command: /bin/systemd-tmpfiles --create
  when: tmpfiles.changed
